### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by flynnamy** [Media-Smart/flexinfer#2]
I checked that volksdep has been installed and could be used. When I run python3 examples/classifier.py test.jpg,it shows core dump. How to fix this?

**Comment by hxcai** [comment]
@flynnamy Hi, could you please provide your code and environment for analysis?

**Comment by flynnamy** [comment]
> @flynnamy Hi, could you please provide your code and environment for analysis?

I use original code without modify. My environmet is Ubuntu 16.04, cuda 10.2, cudnn 8.0, pytorch 1.4.

**Comment by hxcai** [comment]
@flynnamy We have updated the code and please download the newest one to use.
